In [23]:
import pandas as pd
import numpy as np

In [24]:
df=pd.read_csv('../data/AmesHousing.csv')
df.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [3]:
df.columns=df.columns.str.replace(' ', '_')

In [12]:
len(df.columns)

80

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2930 entries, 0 to 2929
Data columns (total 82 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Order            2930 non-null   int64
 1   PID              2930 non-null   int64
 2   MS_SubClass      2930 non-null   int64
 3   MS_Zoning        2930 non-null   object
 4   Lot_Frontage     2440 non-null   float64
 5   Lot_Area         2930 non-null   int64
 6   Street           2930 non-null   object
 7   Alley            198 non-null    object
 8   Lot_Shape        2930 non-null   object
 9   Land_Contour     2930 non-null   object
 10  Utilities        2930 non-null   object
 11  Lot_Config       2930 non-null   object
 12  Land_Slope       2930 non-null   object
 13  Neighborhood     2930 non-null   object
 14  Condition_1      2930 non-null   object
 15  Condition_2      2930 non-null   object
 16  Bldg_Type        2930 non-null   object
 17  House_Style      2930 non-null   object
 18  Overall_Qual     2930 non-null   int64
 19  Overall_Cond     2930 non-null   int64
 20  Year_Built       2930 non-null   int64
 21  Year_Remod/Add   2930 non-null   int64
 22  Roof_Style       2930 non-null   object
 23  Roof_Matl        2930 non-null   object
 24  Exterior_1st     2930 non-null   object
 25  Exterior_2nd     2930 non-null   object
 26  Mas_Vnr_Type     1155 non-null   object
 27  Mas_Vnr_Area     2907 non-null   float64
 28  Exter_Qual       2930 non-null   object
 29  Exter_Cond       2930 non-null   object
 30  Foundation       2930 non-null   object
 31  Bsmt_Qual        2850 non-null   object
 32  Bsmt_Cond        2850 non-null   object
 33  Bsmt_Exposure    2847 non-null   object
 34  BsmtFin_Type_1   2850 non-null   object
 35  BsmtFin_SF_1     2929 non-null   float64
 36  BsmtFin_Type_2   2849 non-null   object
 37  BsmtFin_SF_2     2929 non-null   float64
 38  Bsmt_Unf_SF      2929 non-null   float64
 39  Total_Bsmt_SF    2929 non-null   float64
 40  Heating          2930 non-null   object
 41  Heating_QC       2930 non-null   object
 42  Central_Air      2930 non-null   object
 43  Electrical       2929 non-null   object
 44  1st_Flr_SF       2930 non-null   int64
 45  2nd_Flr_SF       2930 non-null   int64
 46  Low_Qual_Fin_SF  2930 non-null   int64
 47  Gr_Liv_Area      2930 non-null   int64
 48  Bsmt_Full_Bath   2928 non-null   float64
 49  Bsmt_Half_Bath   2928 non-null   float64
 50  Full_Bath        2930 non-null   int64
 51  Half_Bath        2930 non-null   int64
 52  Bedroom_AbvGr    2930 non-null   int64
 53  Kitchen_AbvGr    2930 non-null   int64
 54  Kitchen_Qual     2930 non-null   object
 55  TotRms_AbvGrd    2930 non-null   int64
 56  Functional       2930 non-null   object
 57  Fireplaces       2930 non-null   int64
 58  Fireplace_Qu     1508 non-null   object
 59  Garage_Type      2773 non-null   object
 60  Garage_Yr_Blt    2771 non-null   float64
 61  Garage_Finish    2771 non-null   object
 62  Garage_Cars      2929 non-null   float64
 63  Garage_Area      2929 non-null   float64
 64  Garage_Qual      2771 non-null   object
 65  Garage_Cond      2771 non-null   object
 66  Paved_Drive      2930 non-null   object
 67  Wood_Deck_SF     2930 non-null   int64
 68  Open_Porch_SF    2930 non-null   int64
 69  Enclosed_Porch   2930 non-null   int64
 70  3Ssn_Porch       2930 non-null   int64
 71  Screen_Porch     2930 non-null   int64
 72  Pool_Area        2930 non-null   int64
 73  Pool_QC          13 non-null     object
 74  Fence            572 non-null    object
 75  Misc_Feature     106 non-null    object
 76  Misc_Val         2930 non-null   int64
 77  Mo_Sold          2930 non-null   int64
 78  Yr_Sold          2930 non-null   int64
 79  Sale_Type        2930 non-null   object
 80  Sale_Condition   2930 non-null   object
 81  SalePrice        2930 non-null   int64
dtypes: float64(11), int64(28), object(43)
memory usage: 1.8+ MB

In [6]:
null_values=df.isnull().sum()
null_values[null_values>0].sort_values(ascending=False)

Pool_QC           2917
Misc_Feature      2824
Alley             2732
Fence             2358
Mas_Vnr_Type      1775
Fireplace_Qu      1422
Lot_Frontage       490
Garage_Qual        159
Garage_Cond        159
Garage_Yr_Blt      159
Garage_Finish      159
Garage_Type        157
Bsmt_Exposure       83
BsmtFin_Type_2      81
Bsmt_Cond           80
Bsmt_Qual           80
BsmtFin_Type_1      80
Mas_Vnr_Area        23
Bsmt_Full_Bath       2
Bsmt_Half_Bath       2
BsmtFin_SF_1         1
BsmtFin_SF_2         1
Electrical           1
Total_Bsmt_SF        1
Bsmt_Unf_SF          1
Garage_Area          1
Garage_Cars          1
dtype: int64

In [9]:
df = df.drop(columns=['Order', 'PID'], errors='ignore')

In [10]:
df.head()

,MS_SubClass,MS_Zoning,Lot_Frontage,Lot_Area,Street,Alley,Lot_Shape,Land_Contour,Utilities,Lot_Config,...,Pool_Area,Pool_QC,Fence,Misc_Feature,Misc_Val,Mo_Sold,Yr_Sold,Sale_Type,Sale_Condition,SalePrice
0,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [ ]:
df['Garage_Cars'].unique()#0

array([ 2.,  1.,  3.,  0.,  4.,  5., nan])

In [22]:
df['Garage_Yr_Blt'].value_counts()#0

Garage_Yr_Blt
2005.0    142
2006.0    115
2007.0    115
2004.0     99
2003.0     92
         ...
1908.0      1
1933.0      1
2207.0      1
1943.0      1
1919.0      1
Name: count, Length: 103, dtype: int64

In [21]:
df['Garage_Area'].isnull().sum()#0

np.int64(1)